<a href="https://colab.research.google.com/github/shreyasanap/Deep-learning-Projects/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available!
Using GPU:Tesla T4


# Creating Tensors

In [ ]:
# using empty: allocates memory with no value existing value is shown
a=torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros : initialise bias
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand: weight initialisation
torch.rand(2,3)

tensor([[0.3503, 0.6555, 0.7667],
        [0.2269, 0.7555, 0.6458]])

In [ ]:
#  use of seed: same val u want everytime u run
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

# Other ways of creating tensors

In [ ]:
# using arange
print("using arange ->",torch.arange(0,10,2)) # jump of 2
print("\n")

# using linear space
print("using linspace->",torch.linspace(0,10,10)) # last 10 are val which are evenly spaced
print("\n")

# using eye : identity matrix (diag are ones)
print("using eye ->",torch.eye(5))
print("\n")

# using full:every item i want is 5
print("using full ->",torch.full((3,3),5))


using arange -> tensor([0, 2, 4, 6, 8])


using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # same shape but diff vals

tensor([[                 0,       712964571136,                171],
        [611363658005544960, 467254491549008252, 336362597247222956]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Tensor Data Types

In [ ]:
# find data types
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

1. Scalar Operations

In [ ]:
# addition
x+2
# subtraction
x-2
# multiplication
x*3
# division
x/3
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

2. Element wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])
tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])


In [ ]:
# addition
a+b

# subtract
a-b

tensor([[-0.4491, -0.7447, -0.2103],
        [-0.7834, -0.8752, -0.0209]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# neg
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
# round
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp: keep it in rangethreshold kinda) -> 1.9 = 2 and 3.7 becomes 3
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction operation

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[4., 3., 8.],
        [7., 4., 6.]])

In [ ]:
# sum
torch.sum(e)

tensor(32.)

In [ ]:
# sum along columns
torch.sum(e,dim=0)

tensor([11.,  7., 14.])

In [ ]:
# sum along rows
torch.sum(e,dim=1)

tensor([15., 17.])

In [ ]:
# mean : works only for float
torch.mean(e)

tensor(5.3333)

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max min
torch.max(e)
torch.min(e)

tensor(3.)

In [ ]:
torch.prod(e)

torch.std(e)

torch.var(e)

torch.argmax(e) # gives the index of max val

torch.argmin(e) # gives the index of min val

tensor(1)

# Matrix Operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[0, 1, 9],
        [9, 8, 0]])
tensor([[7, 0],
        [0, 9],
        [5, 7]])


In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[45, 72],
        [63, 72]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [ ]:
# dot product
torch.dot(vector1,vector2)

# 3*1+4*2=11

tensor(11)

In [ ]:
# transpose
f

tensor([[0, 1, 9],
        [9, 8, 0]])

In [ ]:
torch.transpose(f,0,1)
# 0: dim to be swapped
# 1: swap with the col

tensor([[0, 9],
        [1, 8],
        [9, 0]])

In [ ]:
g=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
g

tensor([[3., 9., 4.],
        [0., 5., 7.],
        [5., 9., 9.]])

In [ ]:
torch.det(g)
# ad-bc

tensor(161.)

In [ ]:
torch.inverse(g)

tensor([[-0.1118, -0.2795,  0.2671],
        [ 0.2174,  0.0435, -0.1304],
        [-0.1553,  0.1118,  0.0932]])

# Comparison Operators

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[7, 5, 9],
        [8, 9, 7]])
tensor([[9, 2, 6],
        [7, 7, 8]])


In [ ]:
# greater than
i>j

# less than
i<j

# equal to
i==j

# not equal to
i!=j

# greater than equal to
i>=j
# less than equal to
i<=j

tensor([[ True, False, False],
        [False, False,  True]])

# Special Functions

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10)
k

tensor([[3, 6, 1],
        [5, 5, 0]])

In [ ]:
# log
torch.log(k)
# exp
torch.exp(k)
# sqrt
torch.sqrt(k)
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9975, 0.7311],
        [0.9933, 0.9933, 0.5000]])

In [ ]:
torch.relu(k)

tensor([[3, 6, 1],
        [5, 5, 0]])

# Inplace operation : use underscore (saves space)

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])
tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])


In [ ]:
m+n

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

In [ ]:
m.add_(n) # the val gets added in m itself

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

In [ ]:
m

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

# Copying a tensor

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

In [ ]:
b

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

In [ ]:
a[0][0]=10

In [ ]:
a

tensor([[10.0000,  0.9798,  0.5548],
        [ 0.6868,  0.4920,  0.0748]])

# a's val changed and not b

In [ ]:
b

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

# Tensor Operations on GPU

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b=a.to(device)

# Reshaping Tensors

In [ ]:
a=torch.ones(4,4)

In [ ]:
# reshape
a.reshape(2,2,2,2)

# The first dimension has size 2 (i.e., 2 blocks).
# The second dimension has size 2 (i.e., 2 "rows" per block).
# The third dimension has size 2 (i.e., 2 "columns" per row).
# The fourth dimension has size 2 (i.e., 2 elements per column).

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)

In [ ]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
# unsqueeze

c=torch.rand(226,226,3) # image size

# add a new dimension at that position

In [ ]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
d=torch.rand(1,20)
d

tensor([[0.3780, 0.7077, 0.7936, 0.2313, 0.6106, 0.0260, 0.9428, 0.8335, 0.6601,
         0.2328, 0.9062, 0.9867, 0.5495, 0.1893, 0.8159, 0.7631, 0.0105, 0.1216,
         0.4416, 0.8206]])

In [ ]:
d.squeeze(0).shape

torch.Size([20])

# Numpy & Pytorch (conversion)

In [ ]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

convert to numpy

In [ ]:
b=a.numpy()
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

convert to pytorch tensor

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])